// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// TbUserColumns holds the columns for the "tb_user" table.
	TbUserColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "age", Type: field.TypeInt},
		{Name: "name", Type: field.TypeString, Default: "unknown"},
	}
	// TbUserTable holds the schema information for the "tb_user" table.
	TbUserTable = &schema.Table{
		Name:       "tb_user",
		Columns:    TbUserColumns,
		PrimaryKey: []*schema.Column{TbUserColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		TbUserTable,
	}
)

func init() {
	TbUserTable.Annotation = &entsql.Annotation{
		Table: "tb_user",
	}
}
